spring:
  application:
    name: bank-service
  config:
    import: optional:configserver:http://127.0.0.1:8081
  profiles:
    active: default

#  cloud:
#    config:
#      name: bank-service
#      discovery:
#        service-id: config
#        enabled: true
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lowerCaseServiceId: true

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8082/eureka/
